var idiomList = [
    {id: "1",idiom: "A beehive",meaning: "A busy place",example: "The office was seething like a beehive when she got in",rpt: 1},
    {id: "2",idiom: "A black sheep",meaning: "A person with bad reputation",example: "She had different interests; and we stupidly thought of her as a black sheep.",rpt: 1},
    {id: "3",idiom: "A bolt from the blue",meaning: "Something unexpected and unpleasant",example: "The resignation of the chairman came like a bolt from the blue.",rpt: 4},
    {id: "4",idiom: "A cakewalk",meaning: "An easy achievement",example: "This competition should be a cakewalk. We're bound to win.",rpt: 1},
    {id: "5",idiom: "A chip of the old block",meaning: "Someone who resembles their parent in character or appearance.",example: "Those of us who knew and loved his father will recognise a chip off the old block.",rpt: 1},
    {id: "6",idiom: "A close shave",meaning: "Narrow escape from danger",example: "I had a close shave this morning - some idiot almost knocked me off my bike.",rpt: 2},
    {id: "7",idiom: "A close-fisted person",meaning: "A miser",example: "Ram is a close-fisted person as he never participates in any occasion.",rpt: 3},
    {id: "8",idiom: "A closed book",meaning: "A mystery",example: "Even to his closest friends; he was always something of a closed book.",rpt: 1},
    {id: "9",idiom: "A cuckoo in the nest",meaning: "An unwelcomed intruder",example: "They will; indeed; become cuckoos in the nest; which will be very damaging.",rpt: 1},
    {id: "10",idiom: "A cut above",meaning: "Rather superior to",example: "She's a cut above the other competitors and should win easily.",rpt: 1},
    {id: "11",idiom: "A damp squib",meaning: "A disappointing result",example: "",rpt: 1},
    {id: "12",idiom: "A dark horse",meaning: "An unforeseen competitor",example: "",rpt: 2},
    {id: "13",idiom: "A dog’s breakfast",meaning: "A total mess / A thing that has been done badly",example: "",rpt: 1},
    {id: "14",idiom: "A drop in a bucket",meaning: "A very insignificant amount",example: "",rpt: 1},
    {id: "15",idiom: "A fish out of water",meaning: "In uncomfortable situation",example: "",rpt: 1},
    {id: "16",idiom: "A golden mean",meaning: "Middle course between two extremes",example: "",rpt: 1},
    {id: "17",idiom: "A hard nut to crack",meaning: "A difficult problem or situation to solve or deal with",example: "",rpt: 2},
    {id: "18",idiom: "A house of cards",meaning: "An insecure scheme",example: "",rpt: 1},
    {id: "19",idiom: "A left hand compliment",meaning: "An ambiguous compliment",example: "",rpt: 1},
    {id: "20",idiom: "A little gush of gratitude",meaning: "Excessive enthusiasm",example: "",rpt: 1},
    {id: "21",idiom: "A live wire",meaning: "Lively and active",example: "",rpt: 1},
    {id: "22",idiom: "A man in the street",meaning: "An ordinary person / common man",example: "",rpt: 1},
    {id: "23",idiom: "A man of letters",meaning: "A literary person",example: "",rpt: 2},
    {id: "24",idiom: "A month of sundays",meaning: "A long time",example: "",rpt: 1},
    {id: "25",idiom: "A red letter day",meaning: "An important day",example: "",rpt: 4},
    {id: "26",idiom: "A sacred cow",meaning: "A person never to be criticised",example: "",rpt: 1},
    {id: "27",idiom: "A shot in the dark",meaning: "An attempt to guess something",example: "",rpt: 1},
    {id: "28",idiom: "A sore point",meaning: "Something which hurts",example: "",rpt: 1},
    {id: "29",idiom: "A white elephant",meaning: "Costly or troublesome possession",example: "",rpt: 3},
    {id: "30",idiom: "A wild goose chase",meaning: "Futile search",example: "",rpt: 2},
    {id: "31",idiom: "A wild-goose chase",meaning: "Pointless search",example: "",rpt: 1},
    {id: "32",idiom: "Above board",meaning: "Legal and honest",example: "",rpt: 2},
    {id: "33",idiom: "Achilles’s heel",meaning: "Weak spot",example: "",rpt: 1},
    {id: "34",idiom: "Add fuel to the fire",meaning: "Worsen the situation",example: "",rpt: 2},
    {id: "35",idiom: "All at sea",meaning: "Puzzled",example: "",rpt: 2},
    {id: "36",idiom: "All ears",meaning: "Attentive",example: "",rpt: 1},
    {id: "37",idiom: "All might and main",meaning: "With full force",example: "",rpt: 1},
    {id: "38",idiom: "All moon shine",meaning: "Far from reality",example: "",rpt: 1},
    {id: "39",idiom: "All moonshine",meaning: "Superficial",example: "",rpt: 2},
    {id: "40",idiom: "Allow a free hand",meaning: "Complete liberty",example: "",rpt: 1},
    {id: "41",idiom: "Alma mater",meaning: "Institution where one got education",example: "",rpt: 1},
    {id: "42",idiom: "An about turn",meaning: "Complete change of opinion or situation",example: "",rpt: 1},
    {id: "43",idiom: "An axe to grind",meaning: "A private interest to serve",example: "",rpt: 1},
    {id: "44",idiom: "An open book",meaning: "One that hold no secrets",example: "",rpt: 2},
    {id: "45",idiom: "Apple of discord",meaning: "Cause of animosity",example: "",rpt: 1},
    {id: "46",idiom: "Arm-chair critic",meaning: "A person who give advice based on theory not on practice",example: "",rpt: 1},
    {id: "47",idiom: "Around the clock",meaning: "Day and night",example: "",rpt: 1},
    {id: "48",idiom: "As daft as a brush",meaning: "Extremely silly",example: "",rpt: 1},
    {id: "49",idiom: "As draft as a brush",meaning: "Very silly",example: "",rpt: 1},
    {id: "50",idiom: "As hard as nail",meaning: "Emotionless / To show no sympathy; kindness or fear",example: "",rpt: 1},
    {id: "51",idiom: "At a loss",meaning: "Unable / Not knowing about what to do or say",example: "",rpt: 1},
    {id: "52",idiom: "At a snail’s pace",meaning: "Slowly",example: "",rpt: 1},
    {id: "53",idiom: "At a stone’s throw",meaning: "At short distance",example: "",rpt: 1},
    {id: "54",idiom: "At a stretch",meaning: "Continuously",example: "",rpt: 1},
    {id: "55",idiom: "At draggers drawn",meaning: "Enmity",example: "",rpt: 1},
    {id: "56",idiom: "At loggerheads",meaning: "In strong disagreement",example: "",rpt: 1},
    {id: "57",idiom: "At one's wit's end",meaning: "Puzzled/confused/perplexed",example: "",rpt: 2},
    {id: "58",idiom: "At one’s beck and call",meaning: "Ready to follow orders/ To be dominated by someone",example: "",rpt: 1},
    {id: "59",idiom: "At one’s wit",meaning: "Puzzled/Confused/Perplexed",example: "",rpt: 1},
    {id: "60",idiom: "At random",meaning: "Without any aim or target",example: "",rpt: 1},
    {id: "61",idiom: "At sea",meaning: "At a loss",example: "",rpt: 1},
    {id: "62",idiom: "At sixes and seven",meaning: "In disorder or confusion",example: "",rpt: 1},
    {id: "63",idiom: "At snail’s pace",meaning: "To do things very slowly",example: "",rpt: 1},
    {id: "64",idiom: "At stake",meaning: "In danger/ that can be lost or won depending on the success of a particular action",example: "",rpt: 1},
    {id: "65",idiom: "At stone’s throw",meaning: "Very near",example: "",rpt: 1},
    {id: "66",idiom: "At the eleventh hour",meaning: "At the very last moment",example: "",rpt: 4},
    {id: "67",idiom: "Average out",meaning: "Balance",example: "",rpt: 1},
    {id: "68",idiom: "Back to the drawing board",meaning: "Plan it all over again",example: "",rpt: 1},
    {id: "69",idiom: "Backseat driver",meaning: "A person who gives unwanted advice",example: "",rpt: 1},
    {id: "70",idiom: "Bad blood",meaning: "Angry feeling",example: "",rpt: 4},
    {id: "71",idiom: "Bad hats",meaning: "People of bad character",example: "",rpt: 1},
    {id: "72",idiom: "Balloon goes up",meaning: "The situation turns unpleasant or serious",example: "",rpt: 1},
    {id: "73",idiom: "Barking up the wrong tree",meaning: "Trying to find someone ay wrong place",example: "",rpt: 1},
    {id: "74",idiom: "Batten down the hatches",meaning: "Prepare for a difficult situation",example: "",rpt: 1},
    {id: "75",idiom: "Be down with",meaning: "Suffering from",example: "",rpt: 1},
    {id: "76",idiom: "Be taken aback",meaning: "Shocked or surprised",example: "",rpt: 1},
    {id: "77",idiom: "Bear down",meaning: "To move quickly towards something/someone in a determined or threatening way",example: "",rpt: 1},
    {id: "78",idiom: "Bear in mind",meaning: "Remember",example: "",rpt: 1},
    {id: "79",idiom: "Bear with",meaning: "Support / To be patient with some body or something",example: "",rpt: 1},
    {id: "80",idiom: "Beat about the bush",meaning: "Speak in a round about manner",example: "",rpt: 3},
    {id: "81",idiom: "Beggar description",meaning: "Cannot be described",example: "",rpt: 1},
    {id: "82",idiom: "Beside the mark",meaning: "Irrelevant / Not to be accurate",example: "",rpt: 2},
    {id: "83",idiom: "Beyond the pale",meaning: "Outside commonly accepted standards",example: "",rpt: 2},
    {id: "84",idiom: "Big draw",meaning: "Huge attraction",example: "",rpt: 1},
    {id: "85",idiom: "Bird's eye view",meaning: "An overview",example: "",rpt: 2},
    {id: "86",idiom: "Birds of same feather",meaning: "Persons of same character",example: "",rpt: 1},
    {id: "87",idiom: "Black out",meaning: "Lost consciousness",example: "",rpt: 1},
    {id: "88",idiom: "Blood running cold",meaning: "Become very frightened",example: "",rpt: 1},
    {id: "89",idiom: "Blow one's own trumpet",meaning: "To praise oneself",example: "",rpt: 3},
    {id: "90",idiom: "Blow over",meaning: "Pass off",example: "",rpt: 1},
    {id: "91",idiom: "Blue-eyed boys",meaning: "Favorites",example: "",rpt: 1},
    {id: "92",idiom: "Bone of contention",meaning: "Matter of dispute",example: "",rpt: 2},
    {id: "93",idiom: "Bone to pick",meaning: "Cause of quarrel/ Bone of contention",example: "",rpt: 1},
    {id: "94",idiom: "Born with a silver spoon",meaning: "Born in a rich family",example: "",rpt: 1},
    {id: "95",idiom: "Break down",meaning: "To lose control of your feelings and start crying / Could not proceed",example: "",rpt: 2},
    {id: "96",idiom: "Break in",meaning: "To train somebody or something in something",example: "",rpt: 1},
    {id: "97",idiom: "Break off",meaning: "Suddenly stop",example: "",rpt: 1},
    {id: "98",idiom: "Break the ice",meaning: "Initiate a talk",example: "",rpt: 1},
    {id: "99",idiom: "Break up",meaning: "Disband itself / The breaking up of relationship or association / The division of larger group in smaller fragments",example: "",rpt: 1},
    {id: "100",idiom: "Bring about",meaning: "Cause",example: "",rpt: 2},
    {id: "101",idiom: "Bring down the house",meaning: "Amuse the audience greatly / To make everyone cheer",example: "",rpt: 1},
    {id: "102",idiom: "Bring the house down",meaning: "Make the audience applaud enthusiastically",example: "",rpt: 1},
    {id: "103",idiom: "Brought up",meaning: "Introduce for discussion",example: "",rpt: 1},
    {id: "104",idiom: "Build castle in the air",meaning: "Daydreaming",example: "",rpt: 1},
    {id: "105",idiom: "Bull in a china shop",meaning: "A clumsy person",example: "",rpt: 1},
    {id: "106",idiom: "Burn one’s boat",meaning: "Leave no means of return",example: "",rpt: 1},
    {id: "107",idiom: "Burn your boats",meaning: "Do something that makes it impossible to return ro the previous situation",example: "",rpt: 1},
    {id: "108",idiom: "Bury the hatchet",meaning: "To make peace / To stop being unfriendly and become friends again",example: "",rpt: 4},
    {id: "109",idiom: "Butt in",meaning: "Interrupt",example: "",rpt: 1},
    {id: "110",idiom: "Button one’s lips",meaning: "Stop talking",example: "",rpt: 1},
    {id: "111",idiom: "By fair or foul means",meaning: "In honest or dishonest way",example: "",rpt: 1},
    {id: "112",idiom: "By fits and start",meaning: "Irregularly",example: "",rpt: 1},
    {id: "113",idiom: "By fits and starts",meaning: "Irregularly",example: "",rpt: 4},
    {id: "114",idiom: "By leaps and bound",meaning: "Very rapidly",example: "",rpt: 1},
    {id: "115",idiom: "By leaps and bounds",meaning: "Very Quickly",example: "",rpt: 4},
    {id: "116",idiom: "By the skin of teeth",meaning: "By the narrowest margin",example: "",rpt: 1},
    {id: "117",idiom: "Call for",meaning: "To ask",example: "",rpt: 1},
    {id: "118",idiom: "Call in question",meaning: "Challenge",example: "",rpt: 1},
    {id: "119",idiom: "Call on",meaning: "Pay a visit",example: "",rpt: 1},
    {id: "120",idiom: "Call spade a spade",meaning: "To speak in a straightforward manner",example: "",rpt: 1},
    {id: "121",idiom: "Cannot hold a candle to",meaning: "Cannot be compared to",example: "",rpt: 1},
    {id: "122",idiom: "Cap in hand",meaning: "In a respectful manner",example: "",rpt: 1},
    {id: "123",idiom: "Capital punishment",meaning: "Death sentence",example: "",rpt: 1},
    {id: "124",idiom: "Carrot and stick",meaning: "Reward and punishment policy",example: "",rpt: 1},
    {id: "125",idiom: "Carry out",meaning: "Execute",example: "",rpt: 2},
    {id: "126",idiom: "Carry the ball",meaning: "Be in charge",example: "",rpt: 1},
    {id: "127",idiom: "Carry weight",meaning: "Be important / Important influence",example: "",rpt: 1},
    {id: "128",idiom: "Casting pearl before swine",meaning: "Offering good things to undeserving people",example: "",rpt: 1},
    {id: "129",idiom: "Cat-nap",meaning: "Short sleep",example: "",rpt: 1},
    {id: "130",idiom: "Catch a tartar",meaning: "to deal with a person who is more than one’s match",example: "",rpt: 1},
    {id: "131",idiom: "Catch time by the forelock",meaning: "Seize opportunity",example: "",rpt: 1},
    {id: "132",idiom: "Caught red handed",meaning: "At the time of committing crime",example: "",rpt: 1},
    {id: "133",idiom: "Caught red-handed",meaning: "Discovered in the act of doing",example: "",rpt: 1},
    {id: "134",idiom: "Change colours",meaning: "To turn pale",example: "",rpt: 1},
    {id: "135",idiom: "Chapter and verse",meaning: "Providing minutes details",example: "",rpt: 1},
    {id: "136",idiom: "Cheek by jowl",meaning: "Very near",example: "",rpt: 2},
    {id: "137",idiom: "Chicken out",meaning: "Withdraw / To decide not to do something because you are afraid",example: "",rpt: 1},
    {id: "138",idiom: "Clean hands",meaning: "innocent",example: "",rpt: 1},
    {id: "139",idiom: "Close shave",meaning: "Narrow shave",example: "",rpt: 2},
    {id: "140",idiom: "Close the book",meaning: "Stop working on something",example: "",rpt: 1},
    {id: "141",idiom: "Cock and bull stories",meaning: "Absurd and unlikely stories",example: "",rpt: 1},
    {id: "142",idiom: "Cock and bull story",meaning: "Absurd an unbelievable story",example: "",rpt: 2},
    {id: "143",idiom: "Cold comfort",meaning: "Slight satisfaction",example: "",rpt: 1},
    {id: "144",idiom: "Come out of one’s shell",meaning: "To appear suddenly",example: "",rpt: 1},
    {id: "145",idiom: "Come to grief",meaning: "To suffer",example: "",rpt: 1},
    {id: "146",idiom: "Come to light",meaning: "Been revealed / To become known to people",example: "",rpt: 1},
    {id: "147",idiom: "Cool about working",meaning: "Not tense about working / Reading to work",example: "",rpt: 1},
    {id: "148",idiom: "Cool as cucumber",meaning: "Not nervous or emotional",example: "",rpt: 1},
    {id: "149",idiom: "Cool one’s heel",meaning: "To keep waiting",example: "",rpt: 1},
    {id: "150",idiom: "Cope with",meaning: "compromise",example: "",rpt: 1},
    {id: "151",idiom: "Cordon off",meaning: "Isolate / To stop people from getting into an area by surrounding it with police",example: "",rpt: 1},
    {id: "152",idiom: "Couch potato",meaning: "A person who prefers to watch television",example: "",rpt: 1},
    {id: "153",idiom: "Cross swords",meaning: "Disagree",example: "",rpt: 1},
    {id: "154",idiom: "Cry over spilt milk",meaning: "Cry over irreparable loss",example: "",rpt: 1},
    {id: "155",idiom: "Curry favours",meaning: "Seek favourable attention",example: "",rpt: 1},
    {id: "156",idiom: "Currying favour with",meaning: "Ingratiating / trying too hard to get please somebody",example: "",rpt: 1},
    {id: "157",idiom: "Cut a sorry figure",meaning: "Make a poor impression",example: "",rpt: 1},
    {id: "158",idiom: "Cut and dry method",meaning: "Honest",example: "",rpt: 1},
    {id: "159",idiom: "Cut coat according to one’s cloth",meaning: "Live within your means",example: "",rpt: 1},
    {id: "160",idiom: "Cut no ice",meaning: "Had no influence",example: "",rpt: 2},
    {id: "161",idiom: "Cut one off",meaning: "Disinheriting / To expel from fraternal property",example: "",rpt: 1},
    {id: "162",idiom: "Cut the guardian knot",meaning: "Remove difficulty / To solve problem",example: "",rpt: 1},
    {id: "163",idiom: "Dark horse",meaning: "An unexpected winner",example: "",rpt: 1},
    {id: "164",idiom: "Die hard",meaning: "unwilling to change",example: "",rpt: 1},
    {id: "165",idiom: "Die in harness",meaning: "To die at one’s work",example: "",rpt: 2},
    {id: "166",idiom: "Doctor the accounts",meaning: "To manipulate the accounts",example: "",rpt: 1},
    {id: "167",idiom: "Does not hold water",meaning: "Cannot be believed",example: "",rpt: 1},
    {id: "168",idiom: "Dog in a manger",meaning: "A selfish person",example: "",rpt: 1},
    {id: "169",idiom: "Done for",meaning: "Ruined",example: "",rpt: 1},
    {id: "170",idiom: "Donkey's year",meaning: "A long time",example: "",rpt: 2},
    {id: "171",idiom: "Dot one’s i’s and cross one t’s",meaning: "Be detailed and exact",example: "",rpt: 1},
    {id: "172",idiom: "Down in the dumps",meaning: "Sad and depressed",example: "",rpt: 1},
    {id: "173",idiom: "Drag one’s feet",meaning: "Be reluctant to act",example: "",rpt: 1},
    {id: "174",idiom: "Draw a blank",meaning: "Find no favour",example: "",rpt: 1},
    {id: "175",idiom: "Draw on fancy",meaning: "Use imagination",example: "",rpt: 1},
    {id: "176",idiom: "Draw the line",meaning: "To set a limit",example: "",rpt: 1},
    {id: "177",idiom: "Dressing-down",meaning: "To give scolding",example: "",rpt: 1},
    {id: "178",idiom: "Drive home",meaning: "Emphasise",example: "",rpt: 1},
    {id: "179",idiom: "Dropping like flies",meaning: "Collapsing in large numbers",example: "",rpt: 1},
    {id: "180",idiom: "Dropping names",meaning: "Hinting at high connections/To mention famous people you know or have met in order to impress others",example: "",rpt: 1},
    {id: "181",idiom: "Eat anyone’s salt",meaning: "To be anyone’s guest",example: "",rpt: 1},
    {id: "182",idiom: "Eat humble pie",meaning: "To say or show that you are sorry for the mistakes committed by you",example: "",rpt: 2},
    {id: "183",idiom: "Eat like a horse",meaning: "Eat a lot",example: "",rpt: 1},
    {id: "184",idiom: "Egg someone on",meaning: "TO encourage somebody to do something",example: "",rpt: 1},
    {id: "185",idiom: "Emerge out of thin air",meaning: "Appear Suddenly",example: "",rpt: 1},
    {id: "186",idiom: "End in a fiasco",meaning: "A Total/Utter failure",example: "",rpt: 1},
    {id: "187",idiom: "End in smoke",meaning: "Come to nothing",example: "",rpt: 1},
    {id: "188",idiom: "End up in something",meaning: "Come to nothing/ Useless",example: "",rpt: 1},
    {id: "189",idiom: "Enough rope",meaning: "Enough freedom for action",example: "",rpt: 1},
    {id: "190",idiom: "Evening of life",meaning: "Old age",example: "",rpt: 1},
    {id: "191",idiom: "Every inch a gentleman",meaning: "Entirely",example: "",rpt: 1},
    {id: "192",idiom: "Face the music",meaning: "Get reprimanded",example: "",rpt: 5},
    {id: "193",idiom: "Fair and square",meaning: "Honest",example: "",rpt: 1},
    {id: "194",idiom: "Fair- weather friend",meaning: "A friend that deserts in difficulties",example: "",rpt: 1},
    {id: "195",idiom: "Fair-weather friend",meaning: "Supports only when easy and convenient",example: "",rpt: 1},
    {id: "196",idiom: "Fall back",meaning: "To turn or move back",example: "",rpt: 1},
    {id: "197",idiom: "Fall flat",meaning: "Fail to amuse people / Fail to produce intended effect",example: "",rpt: 1},
    {id: "198",idiom: "Fall short",meaning: "Fail to meet expectation/ have no effect",example: "",rpt: 1},
    {id: "199",idiom: "Fall through",meaning: "To fail",example: "",rpt: 1},
    {id: "200",idiom: "Feather in one's cap",meaning: "An achievement",example: "",rpt: 2},
    {id: "201",idiom: "Feather one’s own nest",meaning: "Make money in an improper way",example: "",rpt: 1},
    {id: "202",idiom: "Feather your nest",meaning: "To make yourself richer; especially by spending money on yourself that should be spent on something else",example: "",rpt: 1},
    {id: "203",idiom: "Fed up",meaning: "Annoyed",example: "",rpt: 1},
    {id: "204",idiom: "Feel blue",meaning: "In trouble / depressed",example: "",rpt: 1},
    {id: "205",idiom: "Feel one’s pulse",meaning: "To find what one is thinking on some point",example: "",rpt: 1},
    {id: "206",idiom: "Fell foul of",meaning: "Got into trouble with",example: "",rpt: 1},
    {id: "207",idiom: "Fight shy of",meaning: "To avoid someone/ something",example: "",rpt: 1},
    {id: "208",idiom: "Fight to the bitter end",meaning: "To fight a losing battle",example: "",rpt: 1},
    {id: "209",idiom: "Fight tooth and nail",meaning: "Fight with strength and fury",example: "",rpt: 2},
    {id: "210",idiom: "Finish with something",meaning: "Be through / To have something at the end / To stop doing something",example: "",rpt: 1},
    {id: "211",idiom: "Fish in troubled water",meaning: "To make a profit out of troubled situation",example: "",rpt: 1},
    {id: "212",idiom: "Fish out of water",meaning: "An uncomfortable position",example: "",rpt: 1},
    {id: "213",idiom: "Fit like a glove",meaning: "Perfectly",example: "",rpt: 1},
    {id: "214",idiom: "Fits and starts",meaning: "Not regularly",example: "",rpt: 1},
    {id: "215",idiom: "Flies off at a tangent",meaning: "Start discussing something irrelevant",example: "",rpt: 1},
    {id: "216",idiom: "Flogging a dead horse",meaning: "Wasting time in useless effort",example: "",rpt: 1},
    {id: "217",idiom: "Floored",meaning: "To surprise or confuse",example: "",rpt: 1},
    {id: "218",idiom: "Flying visit",meaning: "Very short visit",example: "",rpt: 1},
    {id: "219",idiom: "Foam at the mouth",meaning: "Angry",example: "",rpt: 1},
    {id: "220",idiom: "Follow one’s nose",meaning: "To go straight ahead",example: "",rpt: 1},
    {id: "221",idiom: "For all intents and purposes",meaning: "Practically",example: "",rpt: 1},
    {id: "222",idiom: "For better or worse",meaning: "Always",example: "",rpt: 1},
    {id: "223",idiom: "For good",meaning: "Permanently",example: "",rpt: 3},
    {id: "224",idiom: "For keeps",meaning: "Forever",example: "",rpt: 1},
    {id: "225",idiom: "From the bottom of one’s heart",meaning: "To speak frankly",example: "",rpt: 1},
    {id: "226",idiom: "Gate crasher",meaning: "Uninvited guest",example: "",rpt: 1},
    {id: "227",idiom: "Gerrymandering way",meaning: "In a manipulative and unfair way",example: "",rpt: 1},
    {id: "228",idiom: "Get down to business",meaning: "To begin work seriously",example: "",rpt: 1},
    {id: "229",idiom: "Get on nerves",meaning: "Annoying",example: "",rpt: 1},
    {id: "230",idiom: "Get on well",meaning: "Have a friendly relationship",example: "",rpt: 1},
    {id: "231",idiom: "Get the sack",meaning: "dismissed from",example: "",rpt: 2},
    {id: "232",idiom: "Gift of the gab",meaning: "Ability to speak well",example: "",rpt: 3},
    {id: "233",idiom: "Give a hand with",meaning: "To help with",example: "",rpt: 1},
    {id: "234",idiom: "Give a wide berth to",meaning: "To stay away from or avoid someone",example: "",rpt: 1},
    {id: "235",idiom: "Give and take",meaning: "Adjustment / Willingness in relationship to accept what somebody else wants and gives up some of what you want",example: "",rpt: 1},
    {id: "236",idiom: "Give away",meaning: "To distribute something",example: "",rpt: 1},
    {id: "237",idiom: "Give in",meaning: "Yield",example: "",rpt: 2},
    {id: "238",idiom: "Give the game away",meaning: "Give out the secret",example: "",rpt: 2},
    {id: "239",idiom: "Give vent to",meaning: "To emphasize",example: "",rpt: 2},
    {id: "240",idiom: "Give way",meaning: "Collapse",example: "",rpt: 1},
    {id: "241",idiom: "Giving a piece of one’s mind",meaning: "Speak sharply / To disapprove",example: "",rpt: 1},
    {id: "242",idiom: "Go a long way",meaning: "help considerably",example: "",rpt: 1},
    {id: "243",idiom: "Go about",meaning: "Go around / TO continue to do something",example: "",rpt: 1},
    {id: "244",idiom: "Go down the drain",meaning: "Lose forever",example: "",rpt: 1},
    {id: "245",idiom: "Go dutch",meaning: "Divide the cost",example: "",rpt: 1},
    {id: "246",idiom: "Go for the jugular",meaning: "Attack all out / To attack somebody’s weaker point during a discussion",example: "",rpt: 1},
    {id: "247",idiom: "Go haywire",meaning: "Become out of control",example: "",rpt: 1},
    {id: "248",idiom: "Go out of one’s way",meaning: "Do everything possible",example: "",rpt: 1},
    {id: "249",idiom: "Go scot-free",meaning: "To escape without punishment",example: "",rpt: 1},
    {id: "250",idiom: "Go through fire and water",meaning: "Undergo any risk",example: "",rpt: 1},
    {id: "251",idiom: "Go to the dogs",meaning: "To be ruined",example: "",rpt: 2},
    {id: "252",idiom: "Go to the winds",meaning: "Disappear",example: "",rpt: 1},
    {id: "253",idiom: "Going places",meaning: "Talented and successful",example: "",rpt: 2},
    {id: "254",idiom: "Good samaritan",meaning: "Helpful person",example: "",rpt: 1},
    {id: "255",idiom: "Got the sack",meaning: "Dismissed from",example: "",rpt: 1},
    {id: "256",idiom: "Grease anybody’s palm",meaning: "To give bribe",example: "",rpt: 1},
    {id: "257",idiom: "Grease palms",meaning: "To bribe someone",example: "",rpt: 1},
    {id: "258",idiom: "Grease the palm",meaning: "To bribe",example: "",rpt: 1},
    {id: "259",idiom: "Green thumb",meaning: "To have a natural interest",example: "",rpt: 1},
    {id: "260",idiom: "Gut feeling",meaning: "Strong instinct",example: "",rpt: 1},
    {id: "261",idiom: "Had better",meaning: "used for telling somebody what you think he ‘should’ do",example: "",rpt: 1},
    {id: "262",idiom: "Hand in glove",meaning: "In close relationship",example: "",rpt: 2},
    {id: "263",idiom: "Hard and fast",meaning: "Strict",example: "",rpt: 2},
    {id: "264",idiom: "Hard nut to crack",meaning: "Difficult task",example: "",rpt: 1},
    {id: "265",idiom: "Hard of hearing",meaning: "To be deaf",example: "",rpt: 1},
    {id: "266",idiom: "Has a bee in one’s bonnet",meaning: "To be preoccupied or obsessed with something",example: "",rpt: 1},
    {id: "267",idiom: "Have a finger in every pie",meaning: "To be meddlesome / To involved in a lot of different activities and having influence over them",example: "",rpt: 1},
    {id: "268",idiom: "Have something up your sleeve",meaning: "Have an alternate plan",example: "",rpt: 1},
    {id: "269",idiom: "Have the last laugh",meaning: "To be victorious at the end of an argument",example: "",rpt: 1},
    {id: "270",idiom: "Heads will roll",meaning: "Transfers will take place",example: "",rpt: 1},
    {id: "271",idiom: "Heart to heart talk",meaning: "Frank talk",example: "",rpt: 1},
    {id: "272",idiom: "Helter-skelter",meaning: "In disorderly haste",example: "",rpt: 1},
    {id: "273",idiom: "Herculean task",meaning: "A work requiring very great effort",example: "",rpt: 1},
    {id: "274",idiom: "High and dry",meaning: "Neglected/ To leave someone helpless",example: "",rpt: 1},
    {id: "275",idiom: "High handed",meaning: "Using authority in an unreasonable way; overbearing",example: "",rpt: 1},
    {id: "276",idiom: "Hobson’s choice",meaning: "No real choice at all",example: "",rpt: 1},
    {id: "277",idiom: "Hold one’s horses",meaning: "To keep waiting",example: "",rpt: 1},
    {id: "278",idiom: "Hold up",meaning: "Delay",example: "",rpt: 1},
    {id: "279",idiom: "Hold water",meaning: "With logical backing / To stand up to critical examination",example: "",rpt: 2},
    {id: "280",idiom: "Hold your tongue",meaning: "To be silent",example: "",rpt: 1},
    {id: "281",idiom: "Hope against hope",meaning: "Nurture an impossible hope",example: "",rpt: 1},
    {id: "282",idiom: "Horse sense",meaning: "Basic common sense",example: "",rpt: 1},
    {id: "283",idiom: "Husband one’s resource",meaning: "Save / Economical",example: "",rpt: 1},
    {id: "284",idiom: "Ice braking",meaning: "Starting a conversation",example: "",rpt: 1},
    {id: "285",idiom: "In a nutshell",meaning: "Brief",example: "",rpt: 2},
    {id: "286",idiom: "In a pickle",meaning: "In an embarrassing or awkward situation",example: "",rpt: 1},
    {id: "287",idiom: "In a tight corner",meaning: "In a difficult situation",example: "",rpt: 1},
    {id: "288",idiom: "In apple pie order",meaning: "In perfect order",example: "",rpt: 1},
    {id: "289",idiom: "In black and white",meaning: "In writing",example: "",rpt: 2},
    {id: "290",idiom: "In cold blood",meaning: "A murder done without intention",example: "",rpt: 2},
    {id: "291",idiom: "In dutch",meaning: "In trouble",example: "",rpt: 1},
    {id: "292",idiom: "In fits and starts",meaning: "Irregularly",example: "",rpt: 1},
    {id: "293",idiom: "In high spirits",meaning: "Full of hope and enthusiasm",example: "",rpt: 2},
    {id: "294",idiom: "In lieu of",meaning: "Despite of",example: "",rpt: 1},
    {id: "295",idiom: "In the air",meaning: "Certain / Able to be firmly relied on to happen or be the case / Specific but not explicitly named or stated",example: "",rpt: 1},
    {id: "296",idiom: "In the blues",meaning: "Cheerless and depressed",example: "",rpt: 1},
    {id: "297",idiom: "In the good books",meaning: "In favour with boss",example: "",rpt: 2},
    {id: "298",idiom: "In the long run",meaning: "Ultimately",example: "",rpt: 2},
    {id: "299",idiom: "In the loop",meaning: "Informed regularly",example: "",rpt: 1},
    {id: "300",idiom: "In the nick of time",meaning: "Just in time",example: "",rpt: 1},
    {id: "301",idiom: "In the red",meaning: "Losing money/to owe money",example: "",rpt: 1},
    {id: "302",idiom: "In the running",meaning: "Has good prospects in competition",example: "",rpt: 1},
    {id: "303",idiom: "In the soup",meaning: "To be in trouble",example: "",rpt: 1},
    {id: "304",idiom: "In the swim",meaning: "Well informed and up-to-date",example: "",rpt: 1},
    {id: "305",idiom: "In two minds",meaning: "To be undecided",example: "",rpt: 1},
    {id: "306",idiom: "Ins and outs",meaning: "Full details",example: "",rpt: 2},
    {id: "307",idiom: "Iron fist",meaning: "To treat people in severe manner / strictly",example: "",rpt: 1},
    {id: "308",idiom: "Iron will",meaning: "Strong determination",example: "",rpt: 1},
    {id: "309",idiom: "Jumping down one’s throat",meaning: "To react very angrily to somebody",example: "",rpt: 1},
    {id: "310",idiom: "Keep a level head",meaning: "To remain calm and sensible in a difficult situation",example: "",rpt: 1},
    {id: "311",idiom: "Keep an open house",meaning: "Welcome all members",example: "",rpt: 1},
    {id: "312",idiom: "Keep the wolf away from the door",meaning: "To keep off starvation",example: "",rpt: 1},
    {id: "313",idiom: "Keep the wolf from the door",meaning: "Avoid starvation",example: "",rpt: 1},
    {id: "314",idiom: "Keep up with",meaning: "Go at equal pace",example: "",rpt: 1},
    {id: "315",idiom: "Keep wolf away from the door",meaning: "Keep away extreme poverty",example: "",rpt: 1},
    {id: "316",idiom: "Keep your head",meaning: "Remain calm",example: "",rpt: 1},
    {id: "317",idiom: "Kick up a row",meaning: "Make a great fuss / To complain loudly about something",example: "",rpt: 1},
    {id: "318",idiom: "Kicking heels",meaning: "To be relaxed and enjoy / Waste time",example: "",rpt: 1},
    {id: "319",idiom: "Kith and kin",meaning: "Relatives",example: "",rpt: 1},
    {id: "320",idiom: "Know beans about something",meaning: "Well informed and intelligent",example: "",rpt: 1},
    {id: "321",idiom: "Know the ropes",meaning: "Learn the procedures",example: "",rpt: 1},
    {id: "322",idiom: "Lame excuse",meaning: "Unsatisfactory explanation",example: "",rpt: 1},
    {id: "323",idiom: "Lay down arms",meaning: "To surrender",example: "",rpt: 1},
    {id: "324",idiom: "Lay it on thick",meaning: "An exaggeration / To talk about somebody or something in a way than they really are",example: "",rpt: 1},
    {id: "325",idiom: "Lay out",meaning: "Spend",example: "",rpt: 1},
    {id: "326",idiom: "Laying off",meaning: "Dismissal from jobs",example: "",rpt: 1},
    {id: "327",idiom: "Lays out",meaning: "To spend money",example: "",rpt: 1},
    {id: "328",idiom: "Leaps and bounds",meaning: "At rapid pace",example: "",rpt: 3},
    {id: "329",idiom: "Leave high and dry",meaning: "In a difficult situation without help or money / Leave alone to work / A boat in a position out of water",example: "",rpt: 1},
    {id: "330",idiom: "Leave in the lurch",meaning: "Abandon in the midway/difficult situation",example: "",rpt: 2},
    {id: "331",idiom: "Leave no stone unturned",meaning: "To try every possible way",example: "",rpt: 1},
    {id: "332",idiom: "Let sleeping dogs lie",meaning: "Not to bring up an old controversial issue",example: "",rpt: 1},
    {id: "333",idiom: "Let the cat out of the bag",meaning: "To utter a secret carelessly or by mistake",example: "",rpt: 1},
    {id: "334",idiom: "Let the grass grow under the feet",meaning: "Delay in getting things done",example: "",rpt: 1},
    {id: "335",idiom: "Like a phoenix",meaning: "With a new life/rebirth/reincarnation",example: "",rpt: 1},
    {id: "336",idiom: "Live from hand to mouth",meaning: "Miserably",example: "",rpt: 1},
    {id: "337",idiom: "Live-wire",meaning: "A person who is lively or energetic",example: "",rpt: 1},
    {id: "338",idiom: "Look down upon",meaning: "Hate intensely",example: "",rpt: 1},
    {id: "339",idiom: "Look into",meaning: "To investigate",example: "",rpt: 1},
    {id: "340",idiom: "Look sharp",meaning: "Pay attention",example: "",rpt: 1},
    {id: "341",idiom: "Looking forward to",meaning: "To expect something or someone",example: "",rpt: 1},
    {id: "342",idiom: "Lose head",meaning: "Panic",example: "",rpt: 1},
    {id: "343",idiom: "Maiden speech",meaning: "First speech",example: "",rpt: 3},
    {id: "344",idiom: "Make a beeline",meaning: "Rush / To go straight towards something as quick as you can",example: "",rpt: 1},
    {id: "345",idiom: "Make a clean breast",meaning: "Confess without reserve",example: "",rpt: 2},
    {id: "346",idiom: "Make a mockery",meaning: "to make something seem ridiculous or useless / No serious outcome",example: "",rpt: 1},
    {id: "347",idiom: "Make a mountain of a mole hill",meaning: "Exaggerate a minor problem",example: "",rpt: 1},
    {id: "348",idiom: "Make amends for",meaning: "Compensate the loss",example: "",rpt: 1},
    {id: "349",idiom: "Make believe",meaning: "To pretend that something is true",example: "",rpt: 1},
    {id: "350",idiom: "Make both ends mean",meaning: "Live within means",example: "",rpt: 1},
    {id: "351",idiom: "Make both ends meet",meaning: "To live a lavish life",example: "",rpt: 1},
    {id: "352",idiom: "Make ducks and drakes of",meaning: "Squander",example: "",rpt: 1},
    {id: "353",idiom: "Make it light",meaning: "Treat lightly",example: "",rpt: 1},
    {id: "354",idiom: "Make no bones about",meaning: "Do not have any hesitation in anything",example: "",rpt: 1},
    {id: "355",idiom: "Make one’s flesh creep",meaning: "Horrify",example: "",rpt: 1},
    {id: "356",idiom: "Make room",meaning: "Make space",example: "",rpt: 1},
    {id: "357",idiom: "Making hay while the sun shines",meaning: "Taking advantage of a favorable opportunity",example: "",rpt: 1},
    {id: "358",idiom: "Man of letters",meaning: "Proficient in literary arts",example: "",rpt: 1},
    {id: "359",idiom: "Man of straw",meaning: "A man of no substance",example: "",rpt: 2},
    {id: "360",idiom: "Measure up",meaning: "Reach the level",example: "",rpt: 1},
    {id: "361",idiom: "Mend your way’s",meaning: "Improve one’s behaviour",example: "",rpt: 1},
    {id: "362",idiom: "Mince matters",meaning: "To confuse issues/ to mix facts",example: "",rpt: 1},
    {id: "363",idiom: "Nail one’s colours to the mast",meaning: "Refuse to climb down",example: "",rpt: 1},
    {id: "364",idiom: "Nine day’s wonder",meaning: "A dazzling short-lived spectacle of no real value",example: "",rpt: 1},
    {id: "365",idiom: "No hard and fast rules",meaning: "Easy regulation",example: "",rpt: 1},
    {id: "366",idiom: "No love lost between",meaning: "Not on good terms",example: "",rpt: 2},
    {id: "367",idiom: "Not fit to hold candle",meaning: "Not so good as somebody or something else",example: "",rpt: 1},
    {id: "368",idiom: "Not my cup of tea",meaning: "Not what somebody likes or interested in",example: "",rpt: 1},
    {id: "369",idiom: "Not to look a gift horse in the mouth",meaning: "Not to find fault with the gift received",example: "",rpt: 1},
    {id: "370",idiom: "Null and void",meaning: "Empty",example: "",rpt: 3},
    {id: "371",idiom: "Of no avail",meaning: "Useless",example: "",rpt: 1},
    {id: "372",idiom: "Off and on",meaning: "Occasionally",example: "",rpt: 2},
    {id: "373",idiom: "Old head on young shoulder",meaning: "To be wise beyond one’s age",example: "",rpt: 1},
    {id: "374",idiom: "On cloud nine",meaning: "Extremely happy",example: "",rpt: 1},
    {id: "375",idiom: "On good terms",meaning: "Agree with someone",example: "",rpt: 1},
    {id: "376",idiom: "On tenterhooks",meaning: "In suspense and anxiety",example: "",rpt: 1},
    {id: "377",idiom: "On the brink of",meaning: "On the point of",example: "",rpt: 1},
    {id: "378",idiom: "On the cuff",meaning: "On credit",example: "",rpt: 1},
    {id: "379",idiom: "On the horns of dilemma",meaning: "In a situation where you have to make choice between things that are equally unpleasant",example: "",rpt: 1},
    {id: "380",idiom: "On the level",meaning: "Honest and sincere",example: "",rpt: 1},
    {id: "381",idiom: "On the same page",meaning: "Thinks in a similar way",example: "",rpt: 1},
    {id: "382",idiom: "On the spur of the moment",meaning: "To act suddenly; without planning",example: "",rpt: 1},
    {id: "383",idiom: "On the verge of",meaning: "On the brink of",example: "",rpt: 1},
    {id: "384",idiom: "Once in a blue moon",meaning: "Rarely",example: "",rpt: 2},
    {id: "385",idiom: "Other fish to fry",meaning: "Some important work to attend to",example: "",rpt: 1},
    {id: "386",idiom: "Out and out",meaning: "Totally",example: "",rpt: 1},
    {id: "387",idiom: "Out of hand",meaning: "Out of control; at once; immediately",example: "",rpt: 1},
    {id: "388",idiom: "Out of sorts",meaning: "Ill or sick / Upset",example: "",rpt: 1},
    {id: "389",idiom: "Out of the question",meaning: "Undesirable/ Not worth discussing",example: "",rpt: 1},
    {id: "390",idiom: "Out of the world",meaning: "Extraordinary",example: "",rpt: 1},
    {id: "391",idiom: "Out of wits",meaning: "Greatly confused",example: "",rpt: 1},
    {id: "392",idiom: "Over head and ears",meaning: "Completely",example: "",rpt: 1},
    {id: "393",idiom: "Paled into insignificance",meaning: "Seemed less important",example: "",rpt: 1},
    {id: "394",idiom: "Part and parcel",meaning: "An essential part of something",example: "",rpt: 2},
    {id: "395",idiom: "Pay on the nail",meaning: "Pay promptly / Payment without delay",example: "",rpt: 1},
    {id: "396",idiom: "Pay through nose",meaning: "Pay an extremely high price",example: "",rpt: 1},
    {id: "397",idiom: "Penelope’s web",meaning: "An endless job",example: "",rpt: 1},
    {id: "398",idiom: "Pick on",meaning: "Warn severely",example: "",rpt: 1},
    {id: "399",idiom: "Picking up holes in",meaning: "Finding out faults with something",example: "",rpt: 1},
    {id: "400",idiom: "Pin money",meaning: "Additional money",example: "",rpt: 1},
    {id: "401",idiom: "Plain sailing",meaning: "Very easy",example: "",rpt: 1},
    {id: "402",idiom: "Play ducks and drakes",meaning: "Spend lavishly / To waste or squander",example: "",rpt: 1},
    {id: "403",idiom: "Played havoc",meaning: "Caused destruction",example: "",rpt: 1},
    {id: "404",idiom: "Playing to the gallery",meaning: "Befooling the common man",example: "",rpt: 1},
    {id: "405",idiom: "Point blank",meaning: "Very definite and direct",example: "",rpt: 1},
    {id: "406",idiom: "Pore over",meaning: "Go through",example: "",rpt: 1},
    {id: "407",idiom: "Pot luck dinner",meaning: "Dinner where somebody brings something to eat",example: "",rpt: 1},
    {id: "408",idiom: "Pour cats and dogs",meaning: "Rain heavily",example: "",rpt: 1},
    {id: "409",idiom: "Pros and cons",meaning: "Considering all the facts",example: "",rpt: 3},
    {id: "410",idiom: "Pull a fast one",meaning: "Play a trick",example: "",rpt: 1},
    {id: "411",idiom: "Pull a long face",meaning: "Look dejected / An unhappy or disappointed expression",example: "",rpt: 1},
    {id: "412",idiom: "Pull no punch",meaning: "Speaks frankly",example: "",rpt: 1},
    {id: "413",idiom: "Pull strings",meaning: "Use personal influence",example: "",rpt: 1},
    {id: "414",idiom: "Pull together",meaning: "Work harmoniously",example: "",rpt: 1},
    {id: "415",idiom: "Pull up",meaning: "Reprimand",example: "",rpt: 1},
    {id: "416",idiom: "Put across",meaning: "To communicate your ideas; feelings; etc",example: "",rpt: 1},
    {id: "417",idiom: "Put something by",meaning: "To save money for a particular purpose",example: "",rpt: 1},
    {id: "418",idiom: "Put up the shutters",meaning: "Go out of business",example: "",rpt: 1},
    {id: "419",idiom: "Put up with",meaning: "Tolerate",example: "",rpt: 3},
    {id: "420",idiom: "Put your feet down",meaning: "Take a firm stand / To be very strict in opposing what somebody wishes to do",example: "",rpt: 1},
    {id: "421",idiom: "Putting one’s foot down",meaning: "Asserting one’s authority/ take a firm stand",example: "",rpt: 1},
    {id: "422",idiom: "Putting the cart before the horse",meaning: "Doing things in the wrong way",example: "",rpt: 1},
    {id: "423",idiom: "Rack and ruin",meaning: "Ransacked",example: "",rpt: 1},
    {id: "424",idiom: "Rat race",meaning: "Fierce competition for power",example: "",rpt: 1},
    {id: "425",idiom: "Read between the line",meaning: "To understand the inner meaning",example: "",rpt: 1},
    {id: "426",idiom: "Read between the lines",meaning: "Understanding the hidden meaning",example: "",rpt: 3},
    {id: "427",idiom: "Reading between the lines",meaning: "Understanding the hidden meaning",example: "",rpt: 2},
    {id: "428",idiom: "Red herrings",meaning: "Clues intended to distract or mislead / An unimportant fact; idea; event; etc",example: "",rpt: 1},
    {id: "429",idiom: "Red letter day",meaning: "Happy and significant day",example: "",rpt: 1},
    {id: "430",idiom: "Red-letter day",meaning: "An important day",example: "",rpt: 1},
    {id: "431",idiom: "Rest on laurels",meaning: "To be complacent",example: "",rpt: 1},
    {id: "432",idiom: "Rides the high horse",meaning: "Feel superior",example: "",rpt: 1},
    {id: "433",idiom: "Rise with the lark",meaning: "Get up early / To get out of bed very early in the morning",example: "",rpt: 1},
    {id: "434",idiom: "Rub up the wrong way",meaning: "To irk or irritate someone",example: "",rpt: 1},
    {id: "435",idiom: "Rule the roost",meaning: "Exercise authority / To be the most powerful member in the group",example: "",rpt: 1},
    {id: "436",idiom: "Run down",meaning: "Criticise",example: "",rpt: 1},
    {id: "437",idiom: "Run in the same groove",meaning: "Clash with each other",example: "",rpt: 1},
    {id: "438",idiom: "Run into",meaning: "Incurred/to experience difficulties",example: "",rpt: 2},
    {id: "439",idiom: "Run riot",meaning: "Act without restraint",example: "",rpt: 1},
    {id: "440",idiom: "Sail in the same boat",meaning: "To be in same situation",example: "",rpt: 1},
    {id: "441",idiom: "Sailing in the same boat",meaning: "Being in the same difficult situation",example: "",rpt: 1},
    {id: "442",idiom: "Salad days",meaning: "Adolescence",example: "",rpt: 1},
    {id: "443",idiom: "Salt of the earth",meaning: "Good; honest and ideal",example: "",rpt: 1},
    {id: "444",idiom: "Scapegoat",meaning: "A person who is blamed for the wrongdoings; mistakes; or faults of others; especially for reasons of expediency / Fall guy",example: "",rpt: 1},
    {id: "445",idiom: "Scapegoats",meaning: "A person who is blamed for the wrongdoings with arrogant reactions",example: "",rpt: 1},
    {id: "446",idiom: "Scot free",meaning: "Unpunished",example: "",rpt: 1},
    {id: "447",idiom: "Seamy side",meaning: "Unpleasant and immoral",example: "",rpt: 1},
    {id: "448",idiom: "Second thoughts",meaning: "Reconsidering the original idea",example: "",rpt: 1},
    {id: "449",idiom: "See eye to eye",meaning: "To think in same way",example: "",rpt: 2},
    {id: "450",idiom: "See through",meaning: "Detect / To realize the truth about someone or somebody",example: "",rpt: 2},
    {id: "451",idiom: "Selling like hot cakes",meaning: "To have a very good sale",example: "",rpt: 1},
    {id: "452",idiom: "Send packing",meaning: "To tell somebody firmly or rudely to go away / Terminate service",example: "",rpt: 1},
    {id: "453",idiom: "Set one’s face against",meaning: "Oppose strongly",example: "",rpt: 1},
    {id: "454",idiom: "Set the record straight",meaning: "Give a correct account",example: "",rpt: 1},
    {id: "455",idiom: "Shake in shoes",meaning: "Tremble with fear",example: "",rpt: 1},
    {id: "456",idiom: "Shake off",meaning: "Forget / To get away from somebody who is chasing or following you",example: "",rpt: 1},
    {id: "457",idiom: "Sharp practices",meaning: "Dishonest means",example: "",rpt: 1},
    {id: "458",idiom: "Shed crocodile tears",meaning: "To pretend to be sympathetic",example: "",rpt: 1},
    {id: "459",idiom: "Shot in the arm",meaning: "Something that gives encouragement",example: "",rpt: 1},
    {id: "460",idiom: "Show a clean a pair of heels",meaning: "To run away fast / To flee swiftly",example: "",rpt: 1},
    {id: "461",idiom: "Show the white flag",meaning: "T o surrender",example: "",rpt: 1},
    {id: "462",idiom: "Sit in judgement",meaning: "To pass judgement",example: "",rpt: 1},
    {id: "463",idiom: "Sit on the fence",meaning: "To avoid becoming involved in deciding or influencing something",example: "",rpt: 1},
    {id: "464",idiom: "Sitting on the fence",meaning: "Hesitating which side to take",example: "",rpt: 1},
    {id: "465",idiom: "Slip off",meaning: "Leave quietly",example: "",rpt: 1},
    {id: "466",idiom: "Smell the rat",meaning: "Suspect that something is fishy",example: "",rpt: 1},
    {id: "467",idiom: "Snake in the grass",meaning: "A hidden enemy",example: "",rpt: 1},
    {id: "468",idiom: "Soft option",meaning: "Easy and agreeable option",example: "",rpt: 1},
    {id: "469",idiom: "Sought after",meaning: "Wanted by many people because it’s of good quality or difficult to find/Pursued by",example: "",rpt: 1},
    {id: "470",idiom: "Sowing wild oats",meaning: "Irresponsible pleasure seeking in young age",example: "",rpt: 1},
    {id: "471",idiom: "Spick and span",meaning: "Neat and clean / Tidy",example: "",rpt: 1},
    {id: "472",idiom: "Spill the beans",meaning: "Reveal the secret information",example: "",rpt: 1},
    {id: "473",idiom: "Spilling the beans",meaning: "Revealing the information indiscreetly",example: "",rpt: 1},
    {id: "474",idiom: "Spread like fire",meaning: "Spread rapidly",example: "",rpt: 1},
    {id: "475",idiom: "Stand by",meaning: "To help/support somebody or be friend; even in difficult times",example: "",rpt: 2},
    {id: "476",idiom: "Stand on own feet",meaning: "To be independent",example: "",rpt: 1},
    {id: "477",idiom: "Stand-offish",meaning: "Indifferent",example: "",rpt: 1},
    {id: "478",idiom: "Stand/hold your ground",meaning: "Refuse to yield / To continue with your opinions or intentions when someone is opposing you",example: "",rpt: 1},
    {id: "479",idiom: "Standstill",meaning: "Complete halt",example: "",rpt: 1},
    {id: "480",idiom: "Status quo",meaning: "As it is/ unchanged position",example: "",rpt: 1},
    {id: "481",idiom: "Stick to guns",meaning: "Hold on to original decisions",example: "",rpt: 3},
    {id: "482",idiom: "Stir up a hornet’s nest",meaning: "To create a lot of trouble",example: "",rpt: 1},
    {id: "483",idiom: "Stole the show",meaning: "Win everyone’s praise",example: "",rpt: 1},
    {id: "484",idiom: "Strain every nerve",meaning: "Make all efforts / Try all tricks",example: "",rpt: 2},
    {id: "485",idiom: "Straw in the wind",meaning: "An indication of what might happen",example: "",rpt: 1},
    {id: "486",idiom: "Strike a bargain",meaning: "To negotiate a deal",example: "",rpt: 1},
    {id: "487",idiom: "Strom in a tea cup",meaning: "Commotion",example: "",rpt: 1},
    {id: "488",idiom: "Struck a chill to the heart",meaning: "Arouse fear/to make somebody afraid",example: "",rpt: 1},
    {id: "489",idiom: "Swan song",meaning: "Last prayer",example: "",rpt: 1},
    {id: "490",idiom: "Sweep under the carpet",meaning: "Keep hidden",example: "",rpt: 1},
    {id: "491",idiom: "Sweeping statement",meaning: "Thoughtless statement",example: "",rpt: 1},
    {id: "492",idiom: "Take a french leave",meaning: "Being absent without permission",example: "",rpt: 1},
    {id: "493",idiom: "Take a leap in the dark",meaning: "To take risk",example: "",rpt: 1},
    {id: "494",idiom: "Take after",meaning: "Resembles",example: "",rpt: 2},
    {id: "495",idiom: "Take cue from",meaning: "To copy what someone already did in past in order to be successful",example: "",rpt: 1},
    {id: "496",idiom: "Take exception",meaning: "To object over something",example: "",rpt: 3},
    {id: "497",idiom: "Take fancy",meaning: "To attract or please somebody",example: "",rpt: 1},
    {id: "498",idiom: "Take for granted",meaning: "To accept readily/ To pre-suppose as certainly true",example: "",rpt: 1},
    {id: "499",idiom: "Take french leave",meaning: "Absenting oneself without permission",example: "",rpt: 1},
    {id: "500",idiom: "Take hat off",meaning: "Encourage / To admire somebody very much for something he has done",example: "",rpt: 1},
    {id: "501",idiom: "Take the bull by the horns",meaning: "to face a difficulty courageously",example: "",rpt: 1},
    {id: "502",idiom: "Take to heart",meaning: "To be very upset by something that somebody says or does / Serious",example: "",rpt: 1},
    {id: "503",idiom: "Take to one’s heel",meaning: "Run off",example: "",rpt: 1},
    {id: "504",idiom: "Take to task",meaning: "To criticize severely/ to punish",example: "",rpt: 2},
    {id: "505",idiom: "Take with a grain of salt",meaning: "To listen to something with considerable doubt",example: "",rpt: 1},
    {id: "506",idiom: "Talking through hat",meaning: "Talking nonsense",example: "",rpt: 2},
    {id: "507",idiom: "Tall tales",meaning: "Boasting",example: "",rpt: 1},
    {id: "508",idiom: "Teething problems",meaning: "Difficulties at the start",example: "",rpt: 1},
    {id: "509",idiom: "Telling upon",meaning: "Showing effectively / Having strong effect",example: "",rpt: 1},
    {id: "510",idiom: "The alpha and omega",meaning: "Beginning and end",example: "",rpt: 1},
    {id: "511",idiom: "The genomes of zurich",meaning: "A slang term for Swiss bankers",example: "",rpt: 1},
    {id: "512",idiom: "The gift of the gab",meaning: "Ability to speak well",example: "",rpt: 1},
    {id: "513",idiom: "The green-eyed monster",meaning: "Used as a way of talking about jealousy",example: "",rpt: 1},
    {id: "514",idiom: "The jury is out",meaning: "No decision has been reached",example: "",rpt: 1},
    {id: "515",idiom: "The man in the street",meaning: "An ordinary man",example: "",rpt: 1},
    {id: "516",idiom: "The salt of the earth",meaning: "Very good and honest/ Kind",example: "",rpt: 1},
    {id: "517",idiom: "Thick and thin",meaning: "In spite of all difficulties",example: "",rpt: 1},
    {id: "518",idiom: "Through thick and thin",meaning: "Under all circumstances",example: "",rpt: 1},
    {id: "519",idiom: "Throw cold water",meaning: "Discourage",example: "",rpt: 1},
    {id: "520",idiom: "Throw down a glove",meaning: "To accept defeat",example: "",rpt: 1},
    {id: "521",idiom: "Throw dust into one’s eye",meaning: "To deceive",example: "",rpt: 1},
    {id: "522",idiom: "Throw up cards",meaning: "To give in / To blow away the plan",example: "",rpt: 1},
    {id: "523",idiom: "Time and again",meaning: "Always",example: "",rpt: 1},
    {id: "524",idiom: "To add fuel to fire",meaning: "To worsen the matter / To incite",example: "",rpt: 1},
    {id: "525",idiom: "To add fuel to the fire",meaning: "To cause additional anger",example: "",rpt: 2},
    {id: "526",idiom: "To angle",meaning: "To fish",example: "",rpt: 1},
    {id: "527",idiom: "To be all at sea",meaning: "Lost and confused",example: "",rpt: 1},
    {id: "528",idiom: "To be always one’s beck and call",meaning: "At one’s disposal",example: "",rpt: 1},
    {id: "529",idiom: "To be down to earth",meaning: "To be realistic",example: "",rpt: 1},
    {id: "530",idiom: "To be in a fix",meaning: "In a difficult situation",example: "",rpt: 1},
    {id: "531",idiom: "To be in a quandary",meaning: "In a confusing situation",example: "",rpt: 1},
    {id: "532",idiom: "To beat a retreat",meaning: "To run away in fear",example: "",rpt: 1},
    {id: "533",idiom: "To bite the dust",meaning: "To be defeated",example: "",rpt: 1},
    {id: "534",idiom: "To blaze a trail",meaning: "To lead the way as a pioneer",example: "",rpt: 1},
    {id: "535",idiom: "To blow one's own trumpet",meaning: "Praise one’s own abilities and achievements",example: "",rpt: 2},
    {id: "536",idiom: "To break the ice",meaning: "To start a conversation",example: "",rpt: 2},
    {id: "537",idiom: "To bring to light",meaning: "to reveal",example: "",rpt: 2},
    {id: "538",idiom: "To burn candle at both ends",meaning: "To be extravagant/ Spend without any worry",example: "",rpt: 1},
    {id: "539",idiom: "To burn one’s fingers",meaning: "To get physically hurt",example: "",rpt: 1},
    {id: "540",idiom: "To bury the hatchet",meaning: "to make peace",example: "",rpt: 1},
    {id: "541",idiom: "To call it a day",meaning: "To conclude proceedings",example: "",rpt: 2},
    {id: "542",idiom: "To call spade a spade",meaning: "To be frank",example: "",rpt: 1},
    {id: "543",idiom: "To carve out a niche",meaning: "To work harder in order to have successful career / Develop a special position for oneself",example: "",rpt: 1},
    {id: "544",idiom: "To cast a die",meaning: "To take a decision",example: "",rpt: 1},
    {id: "545",idiom: "To catch up with",meaning: "To compete with",example: "",rpt: 1},
    {id: "546",idiom: "To clip one’s wings",meaning: "To deprive one of power",example: "",rpt: 1},
    {id: "547",idiom: "To cut one short",meaning: "To criticize one",example: "",rpt: 1},
    {id: "548",idiom: "To cut one’s coat according to one’s cloth",meaning: "To live within one’s means",example: "",rpt: 1},
    {id: "549",idiom: "To cut teeth",meaning: "To gain experience of something for the first time",example: "",rpt: 1},
    {id: "550",idiom: "To cut the gordian knot",meaning: "To perform a difficult task",example: "",rpt: 1},
    {id: "551",idiom: "To die in harness",meaning: "To die while in service",example: "",rpt: 1},
    {id: "552",idiom: "To eat a humble pie",meaning: "To apologize",example: "",rpt: 2},
    {id: "553",idiom: "To eat humble pie",meaning: "To yield under humiliating circumstances",example: "",rpt: 1},
    {id: "554",idiom: "To end in smoke",meaning: "To come to nothing; no outcome",example: "",rpt: 2},
    {id: "555",idiom: "To explore every avenue",meaning: "To try every opportunity",example: "",rpt: 1},
    {id: "556",idiom: "To face the music",meaning: "To bear the consequences",example: "",rpt: 2},
    {id: "557",idiom: "To fall back on",meaning: "to fail to do something important in time",example: "",rpt: 1},
    {id: "558",idiom: "To feather one's nest",meaning: "To make oneself rich",example: "",rpt: 2},
    {id: "559",idiom: "To feel like a fish out of water",meaning: "Uncomfortable situation",example: "",rpt: 1},
    {id: "560",idiom: "To fight tooth and nail",meaning: "To fight in a determined way for what you want",example: "",rpt: 2},
    {id: "561",idiom: "To flog a dead horse",meaning: "to waste one’s efforts",example: "",rpt: 1},
    {id: "562",idiom: "To foam at one’s mouth",meaning: "To be very angry",example: "",rpt: 1},
    {id: "563",idiom: "To gather roses only",meaning: "To seek all enjoyments of life",example: "",rpt: 1},
    {id: "564",idiom: "To get cold feet",meaning: "Fear",example: "",rpt: 1},
    {id: "565",idiom: "To get into hot water",meaning: "To get into trouble",example: "",rpt: 2},
    {id: "566",idiom: "To get one’s own back",meaning: "To get one’s revenge",example: "",rpt: 1},
    {id: "567",idiom: "To get wind",meaning: "Come to know about something secret or private",example: "",rpt: 1},
    {id: "568",idiom: "To give a piece of mind",meaning: "To reprimand",example: "",rpt: 2},
    {id: "569",idiom: "To give oneself airs",meaning: "Behave arrogantly",example: "",rpt: 1},
    {id: "570",idiom: "To give the devil his due",meaning: "to give encouragement even to the enemy",example: "",rpt: 1},
    {id: "571",idiom: "To give vent to",meaning: "To express a feeling; especially anger; strongly",example: "",rpt: 1},
    {id: "572",idiom: "To go to the whole hog",meaning: "To do it completely",example: "",rpt: 1},
    {id: "573",idiom: "To grease the palm",meaning: "To bribe",example: "",rpt: 1},
    {id: "574",idiom: "To hail from",meaning: "To come from",example: "",rpt: 1},
    {id: "575",idiom: "To have not a leg to stand on",meaning: "Unable to prove or explain why something is reasonable",example: "",rpt: 1},
    {id: "576",idiom: "To have second thoughts",meaning: "To reconsider",example: "",rpt: 1},
    {id: "577",idiom: "To have something up one's sleeve",meaning: "Having a secret plan",example: "",rpt: 2},
    {id: "578",idiom: "To have too many iron in the fire",meaning: "To get engage in too many enterprises at the same time",example: "",rpt: 1},
    {id: "579",idiom: "To hit below the belt",meaning: "To attack unfairly",example: "",rpt: 1},
    {id: "580",idiom: "To hit the jackpot",meaning: "To make money quickly",example: "",rpt: 1},
    {id: "581",idiom: "To keep in abeyance",meaning: "In a state of suspension",example: "",rpt: 1},
    {id: "582",idiom: "To keep the wolf from the door",meaning: "Escape starvation",example: "",rpt: 1},
    {id: "583",idiom: "To keep under wraps",meaning: "Secret",example: "",rpt: 1},
    {id: "584",idiom: "To keep up",meaning: "To keep in touch",example: "",rpt: 1},
    {id: "585",idiom: "To latch onto",meaning: "To promote",example: "",rpt: 1},
    {id: "586",idiom: "To look down one’s nose",meaning: "To regard with contempt",example: "",rpt: 1},
    {id: "587",idiom: "To lose ground",meaning: "To become less popular",example: "",rpt: 1},
    {id: "588",idiom: "To make a mountain of a molehill",meaning: "To give great importance to little things",example: "",rpt: 1},
    {id: "589",idiom: "To make one’s blood boil",meaning: "To make somebody furious",example: "",rpt: 1},
    {id: "590",idiom: "To make things done",meaning: "To manage",example: "",rpt: 1},
    {id: "591",idiom: "To make up one’s mind",meaning: "To decide what to do",example: "",rpt: 1},
    {id: "592",idiom: "To miss the bus",meaning: "To miss an opportunity",example: "",rpt: 1},
    {id: "593",idiom: "To move heaven and earth",meaning: "to try everything possible",example: "",rpt: 1},
    {id: "594",idiom: "To nip in the bud",meaning: "To stop something in the starting",example: "",rpt: 1},
    {id: "595",idiom: "To pass away",meaning: "Die",example: "",rpt: 1},
    {id: "596",idiom: "To pay off old scores",meaning: "To refund old dues",example: "",rpt: 1},
    {id: "597",idiom: "To play fast and loose",meaning: "To act in an unreliable way",example: "",rpt: 1},
    {id: "598",idiom: "To play second fiddle",meaning: "Take a subordinate role",example: "",rpt: 1},
    {id: "599",idiom: "To play to the gallery",meaning: "To behave in an exaggerated way to attract people’s attention",example: "",rpt: 1},
    {id: "600",idiom: "To pull a long face",meaning: "Look sad",example: "",rpt: 1},
    {id: "601",idiom: "To put a spoke in one’s wheel",meaning: "To hinder",example: "",rpt: 1},
    {id: "602",idiom: "To put a spoke in someone’s wheel",meaning: "Destroy the plan / Cause hindrance / To prevent somebody from putting their plan into action",example: "",rpt: 1},
    {id: "603",idiom: "To put an end to",meaning: "Stop",example: "",rpt: 1},
    {id: "604",idiom: "To put in a nutshell",meaning: "To state something very concisely",example: "",rpt: 1},
    {id: "605",idiom: "To put up with",meaning: "To tolerate",example: "",rpt: 1},
    {id: "606",idiom: "To run across",meaning: "To meet by chance",example: "",rpt: 1},
    {id: "607",idiom: "To run one down",meaning: "To disparage someone",example: "",rpt: 1},
    {id: "608",idiom: "To set the thames on fire",meaning: "Do a heroic deed / To do such a work that needs a strenuous effort",example: "",rpt: 1},
    {id: "609",idiom: "To shed crocodile tears",meaning: "To pretend grief",example: "",rpt: 1},
    {id: "610",idiom: "To show a clean pair of heels",meaning: "to escape/run away",example: "",rpt: 1},
    {id: "611",idiom: "To shun evil company",meaning: "To avoid or give up bad company",example: "",rpt: 1},
    {id: "612",idiom: "To smell a rat",meaning: "To suspect a trick",example: "",rpt: 3},
    {id: "613",idiom: "To speak one’s mind",meaning: "To be frank and honest",example: "",rpt: 1},
    {id: "614",idiom: "To spill the beans",meaning: "To reveal a secret",example: "",rpt: 1},
    {id: "615",idiom: "To starve off",meaning: "Postpone",example: "",rpt: 1},
    {id: "616",idiom: "To steer clear of",meaning: "Avoid",example: "",rpt: 1},
    {id: "617",idiom: "To strain every nerve",meaning: "To make utmost efforts",example: "",rpt: 1},
    {id: "618",idiom: "To take after",meaning: "To resemble an older member of family",example: "",rpt: 1},
    {id: "619",idiom: "To take into account",meaning: "To consider",example: "",rpt: 1},
    {id: "620",idiom: "To take someone for a ride",meaning: "to deceive",example: "",rpt: 1},
    {id: "621",idiom: "To take someone to task",meaning: "To scold someone",example: "",rpt: 1},
    {id: "622",idiom: "To take to heart",meaning: "TO be greatly affected",example: "",rpt: 1},
    {id: "623",idiom: "To take to hearts",meaning: "To grieve over",example: "",rpt: 1},
    {id: "624",idiom: "To take to one's heel",meaning: "To run away",example: "",rpt: 2},
    {id: "625",idiom: "To take to task",meaning: "Punish",example: "",rpt: 2},
    {id: "626",idiom: "To talk someone over",meaning: "To convince over",example: "",rpt: 1},
    {id: "627",idiom: "To tell in a nut shell",meaning: "In a brief manner / Summarize",example: "",rpt: 1},
    {id: "628",idiom: "To the letter",meaning: "Paying attention to every detail / Doing or following exactly what somebody something says",example: "",rpt: 1},
    {id: "629",idiom: "To throw dust in one’s eye",meaning: "To deceive",example: "",rpt: 1},
    {id: "630",idiom: "To toe the line",meaning: "To follow the lead / To follow boss’s orders",example: "",rpt: 1},
    {id: "631",idiom: "To turn a deaf ear",meaning: "To be indifferent",example: "",rpt: 1},
    {id: "632",idiom: "To win laurels",meaning: "to earn great prestige",example: "",rpt: 1},
    {id: "633",idiom: "Token strike",meaning: "Short strike held as warning",example: "",rpt: 1},
    {id: "634",idiom: "Too fond of one’s own voice",meaning: "To like talking without wanting to listen to other people/Very selfish",example: "",rpt: 1},
    {id: "635",idiom: "Took after",meaning: "Similar to / to look or behave like an older member of your family",example: "",rpt: 1},
    {id: "636",idiom: "Took to heels",meaning: "Run away in fear",example: "",rpt: 1},
    {id: "637",idiom: "Turn a deaf ear",meaning: "Disobey",example: "",rpt: 3},
    {id: "638",idiom: "Turn a deaf year",meaning: "Disregard/ignore/refuse",example: "",rpt: 1},
    {id: "639",idiom: "Turn an honest living",meaning: "Make an legitimate living",example: "",rpt: 1},
    {id: "640",idiom: "Turn down",meaning: "Refuse",example: "",rpt: 3},
    {id: "641",idiom: "Turn one’s head",meaning: "To feel proud in a way that other people find it annoying",example: "",rpt: 1},
    {id: "642",idiom: "Turn up",meaning: "To appear",example: "",rpt: 1},
    {id: "643",idiom: "Turn up one's nose at",meaning: "To reject/despises",example: "",rpt: 2},
    {id: "644",idiom: "Turn-turtle",meaning: "Complete over-turn of a situation",example: "",rpt: 1},
    {id: "645",idiom: "Under a cloud",meaning: "Under suspicion",example: "",rpt: 4},
    {id: "646",idiom: "Under the thumb of",meaning: "Under the control of",example: "",rpt: 1},
    {id: "647",idiom: "Under the weather",meaning: "Sick",example: "",rpt: 1},
    {id: "648",idiom: "Up to the mark",meaning: "According to the required standard",example: "",rpt: 1},
    {id: "649",idiom: "Vexed question",meaning: "Controversial issue",example: "",rpt: 1},
    {id: "650",idiom: "Vote with your feet",meaning: "Showing your disapproval",example: "",rpt: 1},
    {id: "651",idiom: "Watching grass grow",meaning: "Very boring",example: "",rpt: 1},
    {id: "652",idiom: "Water under the bridge",meaning: "Something that happened in the past and is now forgotten or no longer important",example: "",rpt: 1},
    {id: "653",idiom: "Weal and woe",meaning: "Ups and downs",example: "",rpt: 2},
    {id: "654",idiom: "Wear and tear",meaning: "Damage",example: "",rpt: 1},
    {id: "655",idiom: "Wear heart on sleeves",meaning: "Express emotions freely",example: "",rpt: 1},
    {id: "656",idiom: "Wears heart on sleeves",meaning: "Express feelings openly",example: "",rpt: 1},
    {id: "657",idiom: "Went to the winds",meaning: "Dissipated/ To be utterly lost",example: "",rpt: 1},
    {id: "658",idiom: "Wet behind ears",meaning: "Young and inexperienced / Naive",example: "",rpt: 1},
    {id: "659",idiom: "Wet behind the ears",meaning: "Young and without experience / Naïve",example: "",rpt: 2},
    {id: "660",idiom: "Wet one’s whistle",meaning: "To have a drink / Moistens one’s throat",example: "",rpt: 1},
    {id: "661",idiom: "White elephant",meaning: "A costly but useless possession",example: "",rpt: 1},
    {id: "662",idiom: "Wide off the mark",meaning: "Irrelevant / Not accurate / Inadequate",example: "",rpt: 1},
    {id: "663",idiom: "Wild goose chase",meaning: "A foolish and useless enterprise",example: "",rpt: 2},
    {id: "664",idiom: "With one voice",meaning: "Unanimously",example: "",rpt: 1},
    {id: "665",idiom: "Within a stone’s throw",meaning: "At a short distance",example: "",rpt: 1},
    {id: "666",idiom: "Without a shilling",meaning: "Disinheriting / To expel from fraternal property",example: "",rpt: 1},
    {id: "667",idiom: "Yeoman’s service",meaning: "Social work",example: "",rpt: 1}
  ]